"""
Markdown documentation generator: Convert OpenAPI schemas to formatted docs.

This module implements BLOCKER #3 (Markdown Format Specification):
- Index file: docs/api/index.md (overview + table of contents)
- Per-endpoint files: docs/api/GET_items.md, docs/api/POST_items_{id}.md, etc.
- Structure: [Summary] [Description] [Parameters] [Responses] [Examples]
"""

from pathlib import Path
from typing import Dict, List
from docsync.models import Endpoint, Schema, Parameter, Response
from docsync.utils import get_logger, write_file, ensure_dir


logger = get_logger(__name__)


class MarkdownFormatter:
    """Generates markdown documentation from schema."""

    # BLOCKER #3: Formal markdown format specification
    INDEX_TEMPLATE = """# {title}

**Version:** {version}

**Base URL:** {base_url}

{description}

## Overview

This API documentation is auto-generated from the OpenAPI 3.1.0 schema.

**Total Endpoints:** {endpoint_count}

## Endpoints

{endpoint_toc}

---

*Last updated: {timestamp}*
*Generated by docsync*
"""

    ENDPOINT_TEMPLATE = """# {method} {path}

{summary}

## Description

{description}

## Parameters

{parameters_section}

## Responses

{responses_section}

## Examples

### Request

```
{method} {path}
```

### Success Response (200)

```json
{{
  "status": "success",
  "message": "Request processed"
}}
```

## See Also

- [Back to Index](index.md)
"""

    @staticmethod
    def endpoint_filename(endpoint: Endpoint) -> str:
        """
        Generate safe filename for endpoint.
        
        Format: METHOD_path_components.md
        Example: GET_items.md, POST_items_{id}.md
        
        Args:
            endpoint: Endpoint object
        
        Returns:
            Safe filename string
        """
        # Replace path separators and curly braces
        path_safe = endpoint.path.replace("/", "_").replace("{", "").replace("}", "")
        filename = f"{endpoint.method}_{path_safe}".lower()
        return f"{filename}.md"

    @staticmethod
    def generate_endpoint_markdown(endpoint: Endpoint) -> str:
        """
        Generate markdown for a single endpoint.
        
        Args:
            endpoint: Endpoint object
        
        Returns:
            Formatted markdown string
        """
        # Parameters section
        if endpoint.parameters:
            params_lines = ["| Name | Type | Required | Description |",
                          "|------|------|----------|-------------|"]
            for param in endpoint.parameters:
                required = "✓" if param.required else "✗"
                params_lines.append(
                    f"| {param.name} | {param.schema_type} | {required} | {param.description} |"
                )
            parameters_section = "\n".join(params_lines)
        else:
            parameters_section = "No parameters required."

        # Responses section
        if endpoint.responses:
            responses_lines = ["| Status | Description | Content-Type |",
                             "|--------|-------------|---------------|"]
            for resp in endpoint.responses:
                responses_lines.append(
                    f"| {resp.status_code} | {resp.description} | {resp.content_type} |"
                )
            responses_section = "\n".join(responses_lines)
        else:
            responses_section = "No responses documented."

        summary = f"**{endpoint.summary}**" if endpoint.summary else "*(No summary)*"
        description = endpoint.description if endpoint.description else "*(No description)*"

        return MarkdownFormatter.ENDPOINT_TEMPLATE.format(
            method=endpoint.method,
            path=endpoint.path,
            summary=summary,
            description=description,
            parameters_section=parameters_section,
            responses_section=responses_section
        )

    @staticmethod
    def generate_index_markdown(schema: Schema) -> str:
        """
        Generate index markdown file.
        
        Args:
            schema: Schema object
        
        Returns:
            Formatted markdown string for index
        """
        # Group endpoints by path
        grouped = schema.endpoints_by_path()
        
        toc_lines = []
        for path in sorted(grouped.keys()):
            endpoints = grouped[path]
            methods = ", ".join(sorted([ep.method for ep in endpoints]))
            toc_lines.append(f"- **{path}** ({methods})")
            for ep in endpoints:
                filename = MarkdownFormatter.endpoint_filename(ep)
                toc_lines.append(f"  - [{ep.method} {ep.path}]({filename})")

        endpoint_toc = "\n".join(toc_lines)
        
        from datetime import datetime
        timestamp = datetime.now().isoformat()

        return MarkdownFormatter.INDEX_TEMPLATE.format(
            title=schema.title,
            version=schema.version,
            base_url=schema.base_url or "*(Not specified)*",
            description=schema.description or "*(No description)*",
            endpoint_count=len(schema.endpoints),
            endpoint_toc=endpoint_toc,
            timestamp=timestamp
        )


class MarkdownGenerator:
    """Generates markdown files from OpenAPI schema."""

    @staticmethod
    def generate(schema: Schema, output_dir: str) -> None:
        """
        Generate markdown documentation files.
        
        Implements atomic writes: all files succeed or operation is rolled back.
        
        Args:
            schema: Parsed OpenAPI Schema
            output_dir: Output directory for markdown files
        
        Raises:
            OSError: If file write fails
        """
        logger.info(f"Generating markdown documentation to {output_dir}")
        
        # Ensure output directory exists
        output_path = ensure_dir(output_dir)

        try:
            # Generate index
            index_content = MarkdownFormatter.generate_index_markdown(schema)
            index_file = output_path / "index.md"
            write_file(str(index_file), index_content)
            logger.info(f"Generated index: {index_file}")

            # Generate endpoint files
            for endpoint in schema.endpoints:
                filename = MarkdownFormatter.endpoint_filename(endpoint)
                endpoint_file = output_path / filename
                
                endpoint_content = MarkdownFormatter.generate_endpoint_markdown(endpoint)
                write_file(str(endpoint_file), endpoint_content)
                logger.info(f"Generated endpoint: {endpoint_file}")

            logger.info(f"Successfully generated {len(schema.endpoints)} endpoint docs + index")

        except OSError as e:
            logger.error(f"Failed to generate markdown files: {e}")
            raise


def generate_markdown(schema: Schema, output_dir: str) -> None:
    """
    Public API: Generate markdown documentation.
    
    Args:
        schema: OpenAPI Schema object
        output_dir: Output directory path
    """
    MarkdownGenerator.generate(schema, output_dir)
